### ISSUE TITLE
excludeMediaQueries regexp not works on some servers

### ISSUE THREAD

**Issue by Londeren** [tijsverkoyen/CssToInlineStyles#91] opened 2014-12-10 13:43 UTC
https://github.com/tijsverkoyen/CssToInlineStyles/blob/master/src/CssToInlineStyles.php#L436
```php
$css = preg_replace('/@media [^{]*{([^{}]|{[^{}]*})*}/', '', $css);
var_dump($css); // is NULL in some servers
```
I don't know because of what it, but i modify regexp to
```php
$css = preg_replace('/@media [^{]*{([^{}]|{.*})*}/', '', $css);
```
and it works fine

Server config
```
mbstring.func_overload = 0
mbstring.internal_encoding = utf-8
Multibyte (japanese) regex support 	= enabled
Multibyte regex (oniguruma) version =	5.9.1 
```

**Comment by tommcc** [comment] 2015-04-01 18:07
I can verify @barryvdh's solution works in my situation.

[https://gist.github.com/tommcc/5fefb8602c0bbbc4b54d](This is the CSS that will break) under the existing regex, but not after the fix. The problem also goes away if I remove ~9-12 child rules, so it seems to be related to regex reaching some complexity limit.

Note that this problem may or may not come up on a given server. It seems to be unrelated to PHP version, but instead the version of PCRE lib installed (8.34 and below breaks, 8.35+ works in my testing of various dev/production servers).

If you're on OSX and want to reproduce the problem easily: the latest version of MAMP exhibits this problem, and latest version of XAMPP does not.

**Comment by jstanden** [comment] 2015-07-22 20:03
I've been running into the same PCRE issue on this line with large CSS blocks from inbound HTML email sources that we run through CssToInlineStyles and HTMLPurifier (in Cerb).  I'm using the most recent code from *master*.

When using PHP-FPM behind Nginx, the FPM process dies and Nginx reports "upstream prematurely closed connection ".  Nothing useful is logged.

I can reproduce the issue on:

* OSX 10.10.3 with PHP-FPM 5.5.16, PCRE 8.36 2014-09-26
* Ubuntu 12.04.5 LTS with PHP-FPM 5.3.10-1ubuntu3.19, PCRE 8.12 2011-01-15

My current test case is a customer's Kohl's receipt with about 23KB of content in a `<style>` block.  If `excludeMediaQueries==false` then the HTML/CSS processes properly.

If `excludeMediaQueries==true`, then this regexp kills the PHP process:

```php
$css = preg_replace('/@media[^{]*{([^{}]|{[^{}]*})*}/', '', $css);
```
As recommended by @barryvdh, this variation works properly and avoids the PCRE issue:

```php
$css = preg_replace('/@media[^{]+\{([\s\S]+?})\s*}/', '', $css);
```

I can verify that the length of the CSS content is reduced from 23KB to 9KB too, so the regexp is definitely matching.  The resulting HTML output from CssToInlineStyles looks exactly the same as what Gmail shows for the same source (i.e. it's not stripping important stylesheet content).

**Comment by keybeth** [comment] 2015-08-06 04:21
I have the same issue in my xamp enviroment, on windows 7. But, with the @barryvdh pattern works fine!!!

**Comment by ligne13** [comment] 2015-10-12 16:36
Hi,
same issue and the pattern suggested by @barryvdh works fine !
pull request ?

**Comment by biwerr** [comment] 2015-12-07 12:49
same issue and the pattern suggested by @barryvdh works for me

changing the pcre.backtrack_limit in php ini doesn't work on windows x64 with xampp and php 5.6

**Comment by MichaelTheLi** [comment] 2016-07-19 11:19
If @barryvdh regex doesn't work for you, you can also try this one:
`$css = preg_replace('/@media [^{]*({(?>[^{}]+|(?1))*})/', '', $css);`

**Comment by stof** [comment] 2016-07-22 09:42
See #146 where I improved the regex to avoid useless backtracking (the media query detecting actually never needs to backtrack once it found a ``@media``)

**Comment by tijsverkoyen** [comment] 2016-09-20 12:28
Not relevant anymore since #146 is merged.

**Closed by tijsverkoyen** 2016-09-20 12:28 UTC
