### ISSUE TITLE
Еmoji icons break after processing by the convert() function

### ISSUE THREAD

**Issue by kva4991** [tijsverkoyen/CssToInlineStyles#239] opened 2022-12-30 12:49 UTC
Hello. Happy New Year!
I have an html string
`text = "<p> 😊 😂 😭 😘 😁 😉 😍 🤔 🤔 😪 😻 👩 🙏 👨 👋 👌 👉 👍 👈 ✋ 👇 👍 👆 👎 ☝ 🤘 🤳 ✌ 🖐 👐  ✊ ✍ 🎤 🎙 🎹 🎸 🎻 📻 🎶 🎵 ❤️ 🎧 📵 👪 </ p>"`
when using the function with such parameters:
tijsverkoyen\css-to-inline-styles\src\CssToInlineStyles.php
```
$text = $cssToInlineStyles->convert(
   '<div class="ck-content">' . $model->text . '</div>%FOTTER%' ,
    file_get_contents(YiiBase::getPathOfAlias('ext') . '/ckeditor5-classic/build/styles.css',
)
```

The output is broken the emoji that are now the letter ð (one letter replaced by a single emoji):
ð ð ð­ ð ð ð ð ð¤ ð¤ ðª ð» ð© ð ð¨ ð ð ð ð ð ✋ ð ð ð ð ☝ ð¤ ð¤³ ✌ ð ð  ✊ ✍ ð¤ ð ð¹ ð¸ ð» ð» ð¶ ðµ ❤️ ð§ ðµ ðª

There is a strange thing: not all emoji icons break.
It seems to me that not all sets of standard emoji are embedded in this function. And because of this, an erroneous conversion occurs.

**Comment by Ugoku** [comment] 2023-01-02 13:25
Duplicate of #237. A PR has been submitted (#238) but not yet merged.

**Closed** 2023-01-03 09:29 UTC
